include: package:flutter_lints/flutter.yaml

# Additional information about this file can be found at
# https://dart.dev/guides/language/analysis-options
analyzer:
  errors:
    unreachable_switch_case: ignore
    sort_child_properties_last: ignore
