name: weather_forecast
description: Flutter project to track weather for a rock'n'roll band staff.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev
version: 1.0.0+1

environment:
  sdk: '>=3.1.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  # Firebase
  firebase_core: ^2.16.0
  firebase_crashlytics: ^3.3.6
  firebase_analytics: ^10.5.0
  firebase_remote_config: ^4.2.6
  
  # State management
  mobx: ^2.2.0
  flutter_mobx: ^2.1.0
  
  # Value equality
  equatable: ^2.0.5
  
  # Service locator
  get_it: ^7.6.4
  
  # Device
  connectivity_plus: ^5.0.0

  # UI
  intl: ^0.18.1
  
  # Remote API
  dio: ^5.3.3
  pretty_dio_logger: ^1.3.1

  # General
  envied: ^0.3.0+3
  app_tracking_transparency: ^2.0.4
  

dev_dependencies:
  flutter_test:
    sdk: flutter
    
  flutter_lints: ^2.0.3
  build_runner: ^2.4.6
  flutter_launcher_icons: ^0.13.1
  mobx_codegen: ^2.4.0 #flutter pub run build_runner watch --delete-conflicting-outputs
  
flutter:
  uses-material-design: true
  assets:
    - lib/presentation/ui/assets/images/svg/
    - lib/presentation/ui/assets/images/png/
