// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCSUpUF6PKvqZeeEaIeeSFfwDfp1fp0RHg',
    appId: '1:174655540783:web:146a5d40bfd8b2606180da',
    messagingSenderId: '174655540783',
    projectId: 'rapha-weather-forecast',
    authDomain: 'rapha-weather-forecast.firebaseapp.com',
    storageBucket: 'rapha-weather-forecast.appspot.com',
    measurementId: 'G-MVR3XHMDL3',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBMwJLSzpntCZ0qkUFFJv3V4S33vb-4omA',
    appId: '1:174655540783:android:bb1beb75df72e15e6180da',
    messagingSenderId: '174655540783',
    projectId: 'rapha-weather-forecast',
    storageBucket: 'rapha-weather-forecast.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC2mRw2ChMk3xI7ckC1hCvLavVp4UjhF4w',
    appId: '1:174655540783:ios:5ba0fa46ea20c61e6180da',
    messagingSenderId: '174655540783',
    projectId: 'rapha-weather-forecast',
    storageBucket: 'rapha-weather-forecast.appspot.com',
    iosBundleId: 'com.rapha.weatherForecast',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC2mRw2ChMk3xI7ckC1hCvLavVp4UjhF4w',
    appId: '1:174655540783:ios:7e1004b3cff6911a6180da',
    messagingSenderId: '174655540783',
    projectId: 'rapha-weather-forecast',
    storageBucket: 'rapha-weather-forecast.appspot.com',
    iosBundleId: 'com.rapha.weatherForecast.RunnerTests',
  );
}
